updated all scripts to use 2026 image updated Dockerfile to have gazebo ignotion, only on amd, arm skip gazebo

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,5 +1,8 @@
 FROM ros:humble-perception
 
+# Populated automatically by buildx (e.g. "amd64", "arm64")
+ARG TARGETARCH
+
 ENV DEBIAN_FRONTEND=noninteractive
 
 # Set timezone (avoid tzdata prompt)
@@ -17,18 +20,38 @@ RUN apt-get update && apt-get install -y \
     ros-humble-moveit ros-humble-depthai-ros ros-humble-moveit-ros-control-interface \
     ros-humble-behaviortree-cpp* ros-humble-ros-testing freeglut3-dev ros-humble-moveit-resources-* \
     ros-humble-realsense2-camera \
-    ros-humble-ur-* \
+    ros-humble-ur \
     ros-humble-omni-base* ros-humble-play-motion2 ros-humble-diagnostic-aggregator \
     libprotobuf-dev protobuf-compiler ros-humble-tf* \
     ros-humble-rmw-cyclonedds-cpp \
     net-tools iproute2
 
-RUN apt-get install -y python3-pip python3-colcon-common-extensions python3-pybind11 cmake libmodbus-dev libmongoclient-dev wget\
-    && wget https://github.com/mikefarah/yq/releases/download/v4.35.1/yq_linux_amd64 -O /usr/bin/yq \
+# Gazebo Classic (gazebo11) is only published for amd64 upstream, so it is not
+# installable when cross-building the arm64 image.
+RUN if [ "$TARGETARCH" = "amd64" ]; then \
+        apt-get update && apt-get install -y \
+            ros-humble-gazebo-ros-pkgs \
+            ros-humble-gazebo-ros2-control ; \
+    else \
+        echo "Skipping Gazebo Classic packages: not available for $TARGETARCH" ; \
+    fi
+
+RUN apt-get update && apt-get install -y python3-pip python3-colcon-common-extensions python3-pybind11 cmake libmodbus-dev libmongoclient-dev wget ros-humble-ament-cmake-auto ros-humble-ament-cmake-core \
+    && wget https://github.com/mikefarah/yq/releases/download/v4.35.1/yq_linux_${TARGETARCH} -O /usr/bin/yq \
     && chmod +x /usr/bin/yq
 
 # Python dependencies
-RUN pip3 install --upgrade scipy depthai trimesh transforms3d ur_rtde
+RUN pip3 install --upgrade scipy depthai trimesh transforms3d
+
+# ur_rtde has no arm64 wheel upstream; building it from source on this image
+# fails because a system-wide setuptools plugin pins packaging>=26.2 while
+# apt's python3-packaging is 21.3, and python3-packaging cannot be upgraded
+# without removing core ROS/colcon build tooling. amd64 only.
+RUN if [ "$TARGETARCH" = "amd64" ]; then \
+        pip3 install --upgrade ur_rtde ; \
+    else \
+        echo "Skipping ur_rtde install: no arm64 wheel and source build is broken on this image" ; \
+    fi
 
 # Create user and group with correct IDs
 ARG GROUP_NAME=drims2
@@ -45,11 +68,17 @@ RUN mkdir -p /home/$USER_NAME/static/drims2_ws/src
 
 WORKDIR /home/$USER_NAME/static/drims2_ws/src
 
-# installing Groot
-RUN wget https://pub-32cef6782a9e411e82222dee82af193e.r2.dev/Groot2-v1.9.0-linux-installer.run
-RUN chmod +x Groot2-v1.9.0-linux-installer.run
-RUN ./Groot2-v1.9.0-linux-installer.run install --root /opt/groot --accept-licenses --default-answer --confirm-command
-RUN ln -s /opt/groot/bin/groot2 /usr/local/bin/groot
+# installing Groot (only published as an x86_64 binary upstream, so it is
+# skipped when cross-building for arm64)
+RUN if [ "$TARGETARCH" = "amd64" ]; then \
+        wget https://pub-32cef6782a9e411e82222dee82af193e.r2.dev/Groot2-v1.9.0-linux-installer.run && \
+        chmod +x Groot2-v1.9.0-linux-installer.run && \
+        ./Groot2-v1.9.0-linux-installer.run install --root /opt/groot --accept-licenses --default-answer --confirm-command && \
+        rm Groot2-v1.9.0-linux-installer.run && \
+        ln -s /opt/groot/bin/groot2 /usr/local/bin/groot ; \
+    else \
+        echo "Skipping Groot2 install: no arm64 build available" ; \
+    fi
 
 # Clone code as root
 RUN git clone https://github.com/CNR-STIIMA-IRAS/easy_motion.git
@@ -60,7 +89,17 @@ RUN vcs import < drims_cells/deps.repos
 
 WORKDIR /home/$USER_NAME/static/drims2_ws
 RUN rosdep update
-RUN rosdep install --from-paths src --ignore-src -r -y
+
+# On arm64, none of the Gazebo-related binary packages are published upstream
+# (neither Gazebo Classic nor the newer gz/ros-gz packages), and neither is
+# ros-humble-omni-base-description. Skip resolving those specific keys there;
+# amd64 installs everything as before.
+RUN if [ "$TARGETARCH" = "amd64" ]; then \
+        rosdep install --from-paths src --ignore-src -r -y ; \
+    else \
+        rosdep install --from-paths src --ignore-src -r -y \
+            --skip-keys "gazebo_ros gazebo_plugins pal_gazebo_plugins gazebo_ros2_control gz_ros2_control ros_gz_sim omni_base_description" ; \
+    fi
 
 # Fix ownership of everything
 RUN chown -R $USER_NAME:$GROUP_NAME /home/$USER_NAME
@@ -71,11 +110,11 @@ WORKDIR /home/$USER_NAME/static/drims2_ws
 
 # 1st build: just build interfaces and messages
 SHELL ["/bin/bash", "-c"]
-RUN source /opt/ros/humble/setup.bash && colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release #--packages-select drims2_msgs
+RUN source /opt/ros/humble/setup.bash && colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-select drims2_msgs
 
 # Add ROS, workspace and Gazebo to bashrc
 RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc
-RUN echo "source /usr/share/gazebo/setup.bash" >> ~/.bashrc
+RUN echo "if [ -f /usr/share/gazebo/setup.bash ]; then source /usr/share/gazebo/setup.bash; fi" >> ~/.bashrc
 RUN echo "export LIBGL_ALWAYS_SOFTWARE=1" >> ~/.bashrc
 RUN echo "if [ -f ~/static/drims2_ws/install/setup.bash ]; then source ~/static/drims2_ws/install/setup.bash; fi" >> ~/.bashrc
 
@@ -101,7 +140,15 @@ WORKDIR /home/$USER_NAME/static/drims2_ws/src
 RUN git clone https://github.com/MerlinLaboratory/udp_to_ros2_bridge.git
 WORKDIR /home/$USER_NAME/static/drims2_ws
 SHELL ["/bin/bash", "-c"]
-RUN source /opt/ros/humble/setup.bash && colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release 
+# On arm64 a handful of packages that require Gazebo (unavailable there, see
+# the rosdep step above) will fail to build; --continue-on-error lets every
+# other package build anyway, and the build is allowed to end non-zero there.
+RUN if [ "$TARGETARCH" = "amd64" ]; then \
+        source /opt/ros/humble/setup.bash && colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release ; \
+    else \
+        source /opt/ros/humble/setup.bash && colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release --continue-on-error \
+            || echo "Some Gazebo-dependent packages could not be built on $TARGETARCH; continuing" ; \
+    fi
 
 WORKDIR /home/$USER_NAME
 
